#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 25 10:16:16 2019

@author: gustavo
"""

import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer

#Creating a variable containing the direction of a book in the computer
book = '/home/gustavo/MIA/Metodos probabilisticos/Tarea 1 - Naive Bayes/Maths/txt/Math_1.txt'

#Open the book 
Math_1 = open(book).read()

#Tokenize the book; create an array where each word and sign is a single element
#Several books contain punkts due to equations, in the terminal you must write:
#                       nltk.download('punkt')
#So that NLTK recognizes that special symbol
Math1 = nltk.word_tokenize(Math_1)

#Remove punctuation signs
#This line gets rid of all non-alphanumeric words or symbols
Math1=[w.lower() for w in Math1 if w.isalpha()]

#Remove stopwords; frequently used words like 'the', 'and', 'in', and so on
stop_words = set(stopwords.words('english')) 

#This says:
#Take each toke 'w' for each token 'w' that is contained in the Math1 corpus AND isn't in stopwords
#Probably you will need to download the stopword for nltk to use them:
#                             nltk.download('stopwords')
filtered_book = [w for w in Math1 if not w in stop_words]

#Remove single character words
#Create a list of any token you want to get rid of and use the same for structure to do so
single_character = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'eg',
                      'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'σi', 'σn',
                      'α', 'β', 'βn', 'xn', 'αv', 'ν', 'ϕ', 'ba', 'ip', 'fi', 'kr', 'fr', 'ij', 
                      'bd', 'nj', 'ac', 'bd', 'hk', 'gc', 'xg', 'dn', 'bi', 'mn', 'αu', 'hg', 
                      'zn', 'nth', 'mmc','gcd', 'cd', 'ub', 'di', 'ad', 'ab','gh', 'στ', 'σ', 'ai',
                      'cis', 'abab', 'aabb', 'id', 'sn', 'ax', 'bx', 'αn','px', 'acr', 'bcs', 'hn',
                      'kx', 'ζ', 'η', 'θ', 'κ', 'λ', 'μ', 'ξ', 'ρ', 'τ', 'φ', 'χ', 'ψ', 
                      'ω', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
                      'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Ω', 'Ψ', 'Σ', 'Π', 
                      'Ξ', 'Λ', 'Θ', 'Δ', 'Γ', 'aβ', 'aβj', 'βj', 'gf', 'pn', 'bp', 'zp', 
                      'bch')

filtered_book = [w for w in filtered_book if not w in single_character]

print(filtered_book)
